# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Philipp Rieth"
# description: >- # this means to ignore newlines until "baseurl:"
subtitle: >-
  Philipp's personal blog on cyber security 
#   My sub title here
email: "contact@philipprieth.com"
url: "https://philipprieth.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
repository: "philipprieth/philipprieth.github.io" # the GitHub repository hosting your site
teaser: "assets/images/profile/thisisme.png" # Used to generate absolute URL to image on homepage.
logo: "/assets/images/icons/favicon.ico"
description: >- # this means to ignore newlines until "baseurl:"
  Philipp's personal blog on cyber security: 
  pentesting how-tos, day-to-day experiences, 
  offensive security, and building stronger defences.
# twitter_username: username
github_username: PhilippRieth
minimal_mistakes_skin: dark # default
search: true
breadcrumbs: true
words_per_minute: 183 # average readers can read 183 words per minute

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  # Biographic information
  name             : "Philipp Rieth" 
  bio              : >
    Cybersecurity expert and penetration tester, blending offensive and defensive security to protect critical infrastructure from threats. 
    Hacking systems before the bad guys do and guiding teams to secure them effectively.
  avatar           : "assets/images/profile/thisisme.png"
  location         : "Melbourne, Australia"
  employer         : "Emerging IT, Melbourne"
  uri              : # "https://philipprieth.com" # URL
  email            : "contact@philipprieth.com" 
  github           : "PhilippRieth"
  # stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    
  # instagram        : # Username
  # lastfm           : # Username
  linkedin         : "philipp-rieth"
  # twitter          : # Username
  # youtube          : # Username

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/philipprieth"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/philipp-rieth/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:contact@philipprieth.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      class: wide
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
      header:
        teaser: /assets/images/icons/favicon-444x250.png
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
